services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /root/Docker/homer/config:/www/assets # Make sure your local config directory exists
    ports:
      - "127.0.0.1:8080:8080" 
    user: 1000:1000 
    environment:
      - INIT_ASSETS=1 
    restart: unless-stopped

