services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - "127.0.0.1:4000:1999 that the server will listen to:19999" # don't change the 1999 port, it is required for Netdata container to work
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    environment:                                                                                                       
      - NETDATA_CLAIM_TOKEN=Pd2mvkpctHabAre5Nug8DfK5jwT6NWLKl7BfjoXVwY2LtTh0IepRLD6-rVas-DbtABXwbyVSFb1W8wjGpqWwhDHOGD0ykDzERcwXIYvvaiKZhXU6MToVzcW5ZGoBwer1u3yUz4U                                                                           
      - NETDATA_CLAIM_URL=https://app.netdata.cloud                                                                    
      - NETDATA_CLAIM_ROOMS=9eaa9390-2f90-45bd-a4f9-e090324a4cd0                                                       
volumes:                                                                                                               
  netdataconfig:                                                                                                       
  netdatalib:                                                                                                          
  netdatacache:    