services:
  pihole:
    image: pihole/pihole:latest
    env_file: .env
    ports:
      - "53:53/tcp"  # Don't use any address here ( must listen LAN AND TAILSCALE VPN )
      - "53:53/udp"  # Don't use any address here ( must listen LAN AND TAILSCALE VPN )
      - "127.0.0.1:8081:80/tcp"   # Web interface for NGINX
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
